### ISSUE TITLE
AttributeError: module 'transformer_engine' has no attribute 'pytorch'

### ISSUE THREAD

**Issue by Lzhang-hub** [NVIDIA/TransformerEngine#1014]
I reinstall `pip install flash-attn==2.6.1` in NGC pytorch docker image 24.06.
When I run train job, I got follow error:
```
Traceback (most recent call last):
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/pretrain_gpt.py", line 8, in <module>
    from megatron.training import get_args
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/training/__init__.py", line 16, in <module>
    from .initialize  import initialize_megatron
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/training/initialize.py", line 18, in <module>
    from megatron.training.arguments import parse_args, validate_args
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/training/arguments.py", line 13, in <module>
    from megatron.core.models.retro.utils import (
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/models/retro/__init__.py", line 12, in <module>
    from .decoder_spec import get_retro_decoder_block_spec
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/models/retro/decoder_spec.py", line 9, in <module>
    from megatron.core.models.gpt.gpt_layer_specs import (
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/models/gpt/__init__.py", line 1, in <module>
    from .gpt_model import GPTModel
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 17, in <module>
    from megatron.core.transformer.transformer_block import TransformerBlock
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/transformer/transformer_block.py", line 16, in <module>
    from megatron.core.transformer.custom_layers.transformer_engine import (
  File "/data1/nfs15/nfs/bigdata/zhanglei/ai-platform/hpc-test/multi-node-train/megatron-lm-train/Megatron-LM/20240411/Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 80, in <module>
    class TELinear(te.pytorch.Linear):
AttributeError: module 'transformer_engine' has no attribute 'pytorch'
```

**Comment by pizts** [comment]
same error

**Comment by timmoon10** [comment]
Can you check if TE has built the required shared libraries? In particular, `/NeMo-Aligner/venv/lib/python3.10/site-packages/transformer_engine` should contain `libtransformer_engine.so` and something that looks like `transformer_engine_torch.cpython-310-x86_64-linux-gnu.so`.

If your TE install has `libtransformer_engine.so` but not `transformer_engine_torch.*.so`, then that means TE did not detect PyTorch during the build process. You can try forcing TE to build with PyTorch support by settting the `NVTE_FRAMEWORK` environment variable:
```bash
NVTE_FRAMEWORK=pytorch pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable
```
See the [TE install instructions](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/installation.html#installation-stable-release).

**Comment by anonym-ssh** [comment]
please help to solve this:


Traceback (most recent call last):
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/cosmos-predict1/cosmos_predict1/diffusion/inference/video2world.py", line 20, in <module>
    from megatron.core import parallel_state
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/__init__.py", line 5, in <module>
    from megatron.core.distributed import DistributedDataParallel
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/distributed/__init__.py", line 8, in <module>
    from .torch_fully_sharded_data_parallel import TorchFullyShardedDataParallel
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/distributed/torch_fully_sharded_data_parallel.py", line 16, in <module>
    from ..models.common.embeddings.language_model_embedding import LanguageModelEmbedding
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/models/common/embeddings/__init__.py", line 3, in <module>
    from .rope_utils import apply_rotary_pos_emb
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/models/common/embeddings/rope_utils.py", line 32, in <module>
    from megatron.core.extensions.transformer_engine import fused_apply_rotary_pos_emb_thd
  File "/home/iitbbsr/Documents/netram/NvidiaCosmos4/Megatron-LM/megatron/core/extensions/transformer_engine.py", line 94, in <module>
    class TELinear(te.pytorch.Linear):
AttributeError: module 'transformer_engine' has no attribute 'pytorch'

**Comment by eliohead** [comment]
same

**Comment by RaiaN** [comment]
The same issue!

**Comment by Roger-Lv** [comment]
same

**Comment by OutofAi** [comment]
+1 the same issue

**Comment by meettyj** [comment]
same

**Comment by xuyoji** [comment]
same error

**Comment by nanfangxiansheng** [comment]
same error,find it strange

**Comment by tkob-vh** [comment]
Try replace the `flash-attn-3` / `flash_attn_3` with `flash-attn` / `flash_attn` in `transformer_engine/pytorch/attention/dot_product_attention/backends.py` ?

**Comment by chenhongjin811** [comment]
same error

**Comment by timmoon10** [comment]
This error message is hard for us to debug. As a convenience, the root `transformer_engine` package attempts to import the extensions for both PyTorch and JAX. However, it's unlikely that users have both available, so we suppress import errors. To get a better error message, please try `import transformer_engine.pytorch` or `import transformer_engine.jax`.
