### ISSUE TITLE
how to use TransformerEngine without flash attention

### ISSUE THREAD

**Issue by v-yunbin** [NVIDIA/TransformerEngine#1123]
I can install TransformerEngine , but my gpu is V100 and can not install flash attention(flash attention is not support V100...), whether can I not use flash attention or use xformer to replace it?

```
    import transformer_engine.pytorch as te
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/__init__.py", line 43, in <module>
    from transformer_engine.pytorch.attention import DotProductAttention
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 74, in <module>
    _flash_attn_version = PkgVersion(get_pkg_version("flash-attn"))
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/importlib/metadata.py", line 531, in version
    return distribution(distribution_name).version
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: flash-attn

The above exception was the direct cause of the following exception:
```

**Comment by ptrendx** [comment]
Hi @v-yunbin. We are looking into making FA an optional dependency to avoid issues like this (as well as the huge compilation time).

Adding @ksivaman who is working on this.

**Comment by ksivaman** [comment]
Are you installing TransformerEngine with the `--no-deps` option? `flash-attn` can be installed on V100

**Comment by v-yunbin** [comment]
I install TransformerEngine as follow steps:
```
git clone --branch stable --recursive https://github.com/NVIDIA/TransformerEngine.git

cd TransformerEngine
export NVTE_FRAMEWORK=pytorch   # Optionally set framework
pip install . 
```

**Comment by v-yunbin** [comment]
flash-attn can be installed on V100,but I get this errors:
```
/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py:3051: UserWarning: window_size should be (-1, 0) or (>=0, 0) for attn_mask_type=causal
  warnings.warn(
Traceback (most recent call last):
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 485, in __init__
    super().__init__(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 5178, in __init__
    self.flash_attention = FlashAttention(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 3099, in __init__
    assert (
AssertionError: FlashAttention maximum version 2.5.8 is supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 359, in __init__
    super().__init__(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 89, in __init__
    self.core_attention = build_module(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 485, in __init__
    super().__init__(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 5178, in __init__
    self.flash_attention = FlashAttention(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 3099, in __init__
    assert (
AssertionError: FlashAttention maximum version 2.5.8 is supported. when instantiating TEDotProductAttention

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_layer.py", line 94, in __init__
    self.self_attention = build_module(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 359, in __init__
    super().__init__(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 89, in __init__
    self.core_attention = build_module(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 485, in __init__
    super().__init__(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 5178, in __init__
    self.flash_attention = FlashAttention(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 3099, in __init__
    assert (
AssertionError: FlashAttention maximum version 2.5.8 is supported. when instantiating TEDotProductAttention when instantiating SelfAttention

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/export.py", line 302, in llm_export
    convert_hf_to_megatron(model, extra_args, args.torch_dtype)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/megatron/convert.py", line 22, in convert_hf_to_megatron
    mg_model = model_provider()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/megatron/model.py", line 61, in model_provider
    model = gpt_model_cls(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/model.py", line 103, in __init__
    self.decoder = TransformerBlock(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 155, in __init__
    self._build_layers()
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 170, in _build_layers
    [
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 171, in <listcomp>
    build_layer(layer_spec, i + 1)
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 166, in build_layer
    return build_module(layer_spec, config=self.config, layer_number=layer_number,)
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_layer.py", line 94, in __init__
    self.self_attention = build_module(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 359, in __init__
    super().__init__(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 89, in __init__
    self.core_attention = build_module(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 107, in build_module
    raise type(e)(f"{str(e)} when instantiating {module.__name__}").with_traceback(
  File "./Megatron-LM/megatron/core/transformer/spec_utils.py", line 99, in build_module
    return module(
  File "./Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 485, in __init__
    super().__init__(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 5178, in __init__
    self.flash_attention = FlashAttention(
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/transformer_engine/pytorch/attention.py", line 3099, in __init__
    assert (
AssertionError: FlashAttention maximum version 2.5.8 is supported. when instantiating TEDotProductAttention when instantiating SelfAttention when instantiating TransformerLayer

```

**Comment by sbhavani** [comment]
@ben-8878 TE currently supports cuDNN attention as default
