### ISSUE TITLE
AttnFuncWithCPAndKVAllGather RuntimeError:  in function nvte_fused_attn_fwd: Invalid combination of data type and sequence length for fused attention.

### ISSUE THREAD

**Issue by conver334** [NVIDIA/TransformerEngine#1276]
I have been testing the context parallel communication methods. When cp_comm_type is set to either "p2p" or "a2a", everything works well. 
However, when cp_comm_type is set to "all_gather", I am encountering the following error.
TE version 1.11.0+c27ee60. 
The model is set to Llama 7B, with type=bf16, TP=1, CP=2, PP=4, DP=1, EP=0, VPP=0, and sequence_length=4096.

```python
[rank6]: Traceback (most recent call last):
[rank6]:   File "./Megatron-LM/pretrain_gpt.py", line 265, in <module>
[rank6]:     pretrain(
[rank6]:   File "./Megatron-LM/megatron/training/training.py", line 361, in pretrain
[rank6]:     iteration, num_floating_point_operations_so_far = train(
[rank6]:   File "./Megatron-LM/megatron/training/training.py", line 1249, in train
[rank6]:     train_step(forward_step_func,
[rank6]:   File "./Megatron-LM/megatron/training/training.py", line 731, in train_step
[rank6]:     losses_reduced = forward_backward_func(
[rank6]:   File "./Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 450, in forward_backward_no_pipelining
[rank6]:     output_tensor, num_tokens = forward_step(
[rank6]:   File "./Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 273, in forward_step
[rank6]:     output_tensor, loss_func = forward_step_func(data_iterator, model)
[rank6]:   File "./Megatron-LM/pretrain_gpt.py", line 193, in forward_step
[rank6]:     output_tensor = model(tokens, position_ids, attention_mask,
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1536, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 305, in forward
[rank6]:     return self.module(*inputs, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/legacy/model/module.py", line 189, in forward
[rank6]:     outputs = self.module(*inputs, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 226, in forward
[rank6]:     hidden_states = self.decoder(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/transformer/transformer_block.py", line 493, in forward
[rank6]:     hidden_states, context = layer(
[rank6]:   File "./Megatron-LM/megatron/core/transformer/transformer_layer.py", line 392, in __call__
[rank6]:     return super(MegatronModule, self).__call__(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/transformer/transformer_layer.py", line 296, in forward
[rank6]:     attention_output_with_bias = self.self_attention(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/transformer/attention.py", line 314, in forward
[rank6]:     core_attn_out = self.core_attention(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "./Megatron-LM/megatron/core/extensions/transformer_engine.py", line 700, in forward
[rank6]:     core_attn_out = super().forward(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 8173, in forward
[rank6]:     return self.fused_attention(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1577, in _call_impl
[rank6]:     result = forward_call(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 437, in _fn
[rank6]:     return fn(*args, **kwargs)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 7197, in forward
[rank6]:     output = attn_forward_func_with_cp(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 4355, in attn_forward_func_with_cp
[rank6]:     out = AttnFuncWithCPAndKVAllGather.apply(*args)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 573, in apply
[rank6]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 3489, in forward
[rank6]:     out_per_step[i], [softmax_lse_per_step[i], rng_states[i]] = fused_attn_fwd(
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/cpp_extensions/fused_attn.py", line 1082, in fused_attn_fwd
[rank6]:     output_tensors = tex.fused_attn_fwd(
[rank6]: RuntimeError: ./TransformerEngine/transformer_engine/common/fused_attn/fused_attn.cpp:644 in function nvte_fused_attn_fwd: Invalid combination of data type and sequence length for fused attention. 

```

**Comment by conver334** [comment]
This issue is caused by cuDNN being too old; I used cuDNN 9.1 for my experiments.

Need cuDNN >= 9.3 at least. [https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/fused_attn/fused_attn.cpp#L159-L164](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/fused_attn/fused_attn.cpp#L159-L164)

This is because all-gather implementation uses bottom_right masking
[https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L3394-L3395](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L3394-L3395)

You can fix the issue using the following command:
```bash
python3 -m pip install nvidia-cudnn-cu12==9.3.y.z
```
