### ISSUE TITLE
logging.h:39 in function check_cublas_: CUBLAS Error: the requested functionality is not supported

### ISSUE THREAD

**Issue by vince62s** [NVIDIA/TransformerEngine#225]
I installed and ran the Mnist example with use-fp8 / use-te, worked fine.

Now I am trying to implement fp8 for OpenNMT-py simply using te.fp8_autocast
Got this error nelow.
Iis this an installation issue or a specific operation related?

```
Traceback (most recent call last):
  File "/home/vincent/nlp/OpenNMT-py/train.py", line 6, in <module>
    main()
  File "/home/vincent/nlp/OpenNMT-py/onmt/bin/train.py", line 67, in main
    train(opt)
  File "/home/vincent/nlp/OpenNMT-py/onmt/bin/train.py", line 52, in train
    train_process(opt, device_id=0)
  File "/home/vincent/nlp/OpenNMT-py/onmt/train_single.py", line 227, in main
    trainer.train(
  File "/home/vincent/nlp/OpenNMT-py/onmt/trainer.py", line 323, in train
    self._gradient_accumulation(
  File "/home/vincent/nlp/OpenNMT-py/onmt/trainer.py", line 588, in _gradient_accumulation
    raise exc
  File "/home/vincent/nlp/OpenNMT-py/onmt/trainer.py", line 573, in _gradient_accumulation
    self.optim.backward(loss)
  File "/home/vincent/nlp/OpenNMT-py/onmt/utils/optimizers.py", line 347, in backward
    loss.backward()
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/transformer_engine/pytorch/module/linear.py", line 367, in backward
    wgrad = fp8_gemm(
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/transformer_engine/pytorch/cpp_extensions.py", line 829, in fp8_gemm
    _ = fn(*args)
  File "/home/vincent/miniconda3/envs/pytorch1.14/lib/python3.10/site-packages/torch/_ops.py", line 646, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: /home/vincent/nlp/TransformerEngine/transformer_engine/common/include/transformer_engine/logging.h:39 in function check_cublas_: CUBLAS Error: the requested functionality is not supported

```

**Comment by nouiz** [comment]
What is the shapes here?
fp8 gemms request all dimensions to be a multiple of 16. Could you hit that issue?

**Comment by vince62s** [comment]
inputmat_t_total
grad_output_t
are sized multiple of 8 before the error.
what else can I check?


wgrad = fp8_gemm(
                            inputmat_t_total,
                            fwd_scale_inverses,
                            tex.FP8FwdTensors.GEMM1_INPUT,
                            fp8_dtype_forward,
                            grad_output_t,
                            ctx.fp8_meta["scaling_bwd"].scale_inv,
                            tex.FP8BwdTensors.GRAD_OUTPUT1,
                            fp8_dtype_backward,
                            ctx.activation_dtype,
                            get_workspace(),
                            accumulate=accumulate_wgrad_into_param_main_grad,
                            out=weight.main_grad if ctx.fuse_wgrad_accumulation else None,
                            use_split_accumulator=_2X_ACC_WGRAD,
                        )

**Comment by timmoon10** [comment]
Try setting `CUBLAS_LOGINFO_DBG=1` and `CUBLAS_LOGDEST_DBG=stderr` in the environment. The logger might give us some more clues. See: https://docs.nvidia.com/cuda/cublas/index.html#cublasloggerconfigure

**Comment by vince62s** [comment]
sorry guys, I messed up between multiple of 8 vs 16
