### ISSUE TITLE
Converting `scaled_dot_product_attention` to `DotProductAttention`

### ISSUE THREAD

**Issue by carmocca** [NVIDIA/TransformerEngine#267]
Hi!

I am testing out TransformerEngine's attention implementation, but I'm not getting numerical parity.

This means I cannot use this layer in my LLM because the weights I'm loading perform worse with it.

Here's the script I'm using:

```python
import math

import torch

B = 1
nh = 8
T = 128
hs = 64

with torch.device("cuda"):
    q = torch.rand(B, nh, T, hs)
    k = torch.rand(B, nh, T, hs)
    v = torch.rand(B, nh, T, hs)
    mask = torch.tril(torch.ones((T, T), dtype=torch.bool)).unsqueeze(0).unsqueeze(0)
scale = 1 / math.sqrt(hs)

y1 = torch.nn.functional.scaled_dot_product_attention(q, k, v, mask, scale=scale, is_causal=False, dropout_p=0.0)

att = (q @ k.transpose(-2, -1)) * scale
att = torch.masked_fill(att, ~mask, torch.finfo(att.dtype).min)
att = torch.nn.functional.softmax(att, dim=-1)
y2 = att @ v  # (B, nh, T, T) x (B, nh, T, hs) -> (B, nh, T, hs)

print(y1.mean(), y2.mean())
torch.testing.assert_close(y1, y2)

from transformer_engine.pytorch import DotProductAttention

att = DotProductAttention(num_attention_heads=nh, kv_channels=hs, attention_dropout=.0, attn_mask_type="padding")
# requires (T, B, nh, hs)
q = q.permute(2, 0, 1, 3)
k = k.permute(2, 0, 1, 3)
v = v.permute(2, 0, 1, 3)
y3 = att(q, k, v, mask)

y1 = y1.permute(3, 0, 1, 2).reshape(T, B, -1)
print(y1.mean(), y3.mean())
torch.testing.assert_close(y1, y3)
```

Output:

```python
tensor(0.4994, device='cuda:0') tensor(0.4994, device='cuda:0')
tensor(0.4994, device='cuda:0') tensor(0.4993, device='cuda:0')
Traceback (most recent call last):
  File "kk.py", line 38, in <module>
    torch.testing.assert_close(y1, y3)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 65525 / 65536 (100.0%)
Greatest absolute difference: 0.6001713275909424 at index (86, 0, 256) (up to 1e-05 allowed)
Greatest relative difference: 2020.320556640625 at index (126, 0, 425) (up to 1.3e-06 allowed)
```

Thanks!

**Comment by cyanguwa** [comment]
Hi @carmocca , I think you might've missed a couple of things in the script. This should be able to fix it:
```import math

import torch

B = 1
nh = 8
T = 128
hs = 64

with torch.device("cuda"):
    q = torch.rand(B, nh, T, hs)
    k = torch.rand(B, nh, T, hs)
    v = torch.rand(B, nh, T, hs)
    mask = torch.tril(torch.ones((T, T), dtype=torch.bool)).unsqueeze(0).unsqueeze(0)
scale = 1 / math.sqrt(hs)

#y1 = torch.nn.functional.scaled_dot_product_attention(q, k, v, mask, scale=scale, is_causal=False, dropout_p=0.0)

att = (q @ k.transpose(-2, -1)) * scale
att = torch.masked_fill(att, ~mask, torch.finfo(att.dtype).min)
att = torch.nn.functional.softmax(att, dim=-1)
y2 = att @ v  # (B, nh, T, T) x (B, nh, T, hs) -> (B, nh, T, hs)

#print(y1.mean(), y2.mean())
#torch.testing.assert_close(y1, y2)

from transformer_engine.pytorch import DotProductAttention

att = DotProductAttention(num_attention_heads=nh, kv_channels=hs, attention_dropout=.0, attn_mask_type="padding")
# requires (T, B, nh, hs)
q = q.permute(2, 0, 1, 3)
k = k.permute(2, 0, 1, 3)
v = v.permute(2, 0, 1, 3)
y3 = att(q, k, v, ~mask)

#y1 = y1.permute(3, 0, 1, 2).reshape(T, B, -1)
y2 = y2.permute(2, 0, 1, 3).reshape(T, B, -1)
print(y2.mean(), y3.mean())
torch.testing.assert_close(y2, y3)
```

Results:
```
tensor(0.5008, device='cuda:0') tensor(0.5008, device='cuda:0')
```
I didn't test `y1` but based on your previous test, `y1` should be equal to `y2`.

**Comment by carmocca** [comment]
You are totally right. What a silly mistake! Thanks
