### ISSUE TITLE
      ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by conceptofmind** [NVIDIA/TransformerEngine#298]
Hi all,

I am currently receiving the error below when trying to install.

Install:
```
NVTE_FRAMEWORK=pytorch pip install --upgrade git+https://github.com/NVIDIA/TransformerEngine.git@stable
```
Error:
```
Collecting flash-attn>=1.0.2 (from transformer-engine==0.9.0)
  Using cached flash_attn-1.0.7.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/miniconda3/envs/finetune/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/miniconda3/envs/finetune/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/miniconda3/envs/finetune/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-5fq6214t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-5fq6214t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-5fq6214t/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
```
I currently have PyTorch for CUDA 11.8 installed which is a pre-requisite in the documentation. I tried with PyTorch CUDA 12.1 and I am still having the same issue.

It looks like this is a Flash Attention issue which is causing problems when installing TE.

Thank you,

Enrico

**Comment by DD-DuDa** [comment]
I have the same issue. I can only install TE by using Docker

**Comment by ptrendx** [comment]
It looks like the same issue as this one: https://github.com/HazyResearch/flash-attention/issues/284

Which pyTorch version do you have?

**Comment by conceptofmind** [comment]
> It looks like the same issue as this one: [HazyResearch/flash-attention#284](https://github.com/HazyResearch/flash-attention/issues/284)
> 
> Which pyTorch version do you have?

Hi,

I tried with PyTorch 2.0.1 with cu118:
```
Name: torch
Version: 2.0.1+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Requires: filelock, jinja2, networkx, sympy, triton, typing-extensions
Required-by: accelerate, deepspeed, torchaudio, torchvision, triton
```
And PyTorch 2.1.0 with cu121:
```
Name: torch
Version: 2.1.0.dev20230626+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Requires: filelock, fsspec, jinja2, networkx, pytorch-triton, sympy, typing-extensions
Required-by: torchaudio, torchvision
```

Thank you,

Enrico

**Comment by fecet** [comment]
https://github.com/HazyResearch/flash-attention/pull/283

**Comment by lifehacking** [comment]
I have the same issue，torch version 2.0.1+cu118，how to fix？

**Comment by tangjiangling** [comment]
Try this: `pip install flash-attn --no-build-isolation`

See https://github.com/Dao-AILab/flash-attention/issues/246#issuecomment-1570190203
