### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by quanliu1991** [NVIDIA/TransformerEngine#325]
import transformer_engine
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c7f260fc8e1b>", line 1, in <module>
    import transformer_engine
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/__init__.py", line 9, in <module>
    from . import pytorch
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/__init__.py", line 6, in <module>
    from .module import LayerNormLinear
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module/__init__.py", line 6, in <module>
    from .layernorm_linear import LayerNormLinear
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module/layernorm_linear.py", line 16, in <module>
    from .base import (
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/module/base.py", line 20, in <module>
    from ..fp8 import (
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/pytorch/fp8.py", line 13, in <module>
    from transformer_engine.common.recipe import DelayedScaling, Format
  File "/root/.pycharm_helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformer_engine/common/recipe.py", line 53, in <module>
    class DelayedScaling:
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 336, in pydantic.dataclasses._add_pydantic_validation_attributes
  File "pydantic/dataclasses.py", line 391, in pydantic.dataclasses.create_pydantic_model_from_dataclass
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 663, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

env:
python. 3.8.10
transformer-engine       0.10.0+96ed6fc
torch                    2.0.1
flash-attn            1.0.7

**Comment by quanliu1991** [comment]
pydantic 1.10.2 ->2.0.3 is work.
