### ISSUE TITLE
[PyTorch] Multiquery attention: `TransformerLayer.kv_channels` causes errors

### ISSUE THREAD

**Issue by danthe3rd** [NVIDIA/TransformerEngine#337]
### Repro code
```
import time
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity
import transformer_engine.pytorch as te
from transformer_engine.common import recipe

dim, n_heads = 3 * 128, 3
seqlen = 128
batch_size = 2

model = te.TransformerLayer(
    hidden_size=dim,
    ffn_hidden_size=dim * 4,
    num_attention_heads=n_heads,
    kv_channels=1)
model.to("cuda").to(torch.float16)
inp = torch.randn([
    batch_size,
    seqlen,
    dim], device="cuda", dtype=torch.float16, requires_grad=True)

model(inp)
```

### Output
```
Traceback (most recent call last):
  File "/home/user/bench/bug_fp8.py", line 23, in <module>
    model(inp)
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TransformerEngine/transformer_engine/pytorch/transformer.py", line 479, in forward
    self_attention_outputs = self.self_attention(
                             ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1522, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1531, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/TransformerEngine/transformer_engine/pytorch/attention.py", line 1222, in forward
    mixed_x_layer = mixed_x_layer.view(*new_tensor_shape)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[2, 128, 9, 1]' is invalid for input of size 294912
```

### Versions:
Transformer engine latest as of today (https://github.com/NVIDIA/TransformerEngine/commit/7a30ba45317176c00e51121275e71a6e647ea561)
Same as in https://github.com/NVIDIA/TransformerEngine/issues/336

**Comment by ptrendx** [comment]
@cyanguwa could you take a look?

**Comment by cyanguwa** [comment]
Hi @danthe3rd,

Shouldn't the `kv_channels` be 128 based on your `hidden_size`? Also, to use the multi-query feature of attention, please try specifying `num_gqa_groups = 1`. The `num_attention_heads` specifies the number of heads in the queries, while `num_gqa_groups` specifies the number of heads in the keys and values. If unspecified, `num_gqa_groups` will be equal to `num_attention_heads`.

Thanks,
Charlene

**Comment by cyanguwa** [comment]
@danthe3rd Hope this issue has been resolved? Let me know if you're still experiencing any issues with this code? Thanks!

**Comment by danthe3rd** [comment]
Hi @cyanguwa 
The issue is resolved, thank you :)
Closing
