### ISSUE TITLE
FSDP support

### ISSUE THREAD

**Issue by yongyanrao** [NVIDIA/TransformerEngine#401]
I was wondering if PyTorch's FullyShardedDataParallel (FSDP) is supported by TransformerEngine , especially if FP8 can work with FSDP. Thank you in advance.

**Comment by timmoon10** [comment]
In the current scheme, Transformer Engine modules use standard parameter tensors in standard dtypes (FP32/BF16/FP16). Optimizers typically require higher precision than FP8 to get good learning behavior. I don't see anything that would disrupt FSDP and I've been able to get TE and FSDP working together in some quick experiments.

**Comment by yongyanrao** [comment]
Hi Tim, thank you for the response. Did you try FP8 + FSDP yet?

**Comment by MatthieuToulemont** [comment]
Hello, @timmoon10 which FSDP did you use ? Fairscale's ?

**Comment by yongyanrao** [comment]
Hi, I was referring to pytorch's FullyShardedDataParallel.

**Comment by MatthieuToulemont** [comment]
Thank you !

**Comment by timmoon10** [comment]
Yep, I used [PyTorch FSDP](https://pytorch.org/docs/stable/fsdp.html). Be advised I haven't done full convergence experiments, just some basic sanity checking.

**Comment by jramapuram** [comment]
What is the recommendation for MixedPrecision when using FP8 with FSDP @timmoon10 ?

```python
from torch.distributed.fsdp import MixedPrecision

precision = ?

MixedPrecision(
    param_dtype=precision,  # should we be forcing dtype here?
    reduce_dtype=torch.float32,  # reduce in FP32 as with AMP?
    buffer_dtype=precision,  # buffers in FP32?
    cast_forward_inputs=is_amp_enabled,  # should we cast the forward samples?
)
```

**Comment by timmoon10** [comment]
Transformer Engine manages FP8 casting internally (see [`transformer_engine.pytorch.fp8_autocast`](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/api/pytorch.html?highlight=autocast#transformer_engine.pytorch.fp8_autocast)) and it can run into problems when combined with other mixed precision tools like [`torch.autocast`](https://pytorch.org/docs/stable/amp.html#torch.autocast) or [`torch.distributed.fsdp.MixedPrecision`](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.MixedPrecision). For the moment, FSDP mixed precision should only be used to handle the case where `param_dtype` and `reduce_dtype` do not match, e.g.:
```python
from torch.distributed.fsdp import MixedPrecision
import transformer_engine.pytorch as te

precision = torch.bfloat16
model = te.Linear(32, 32, params_dtype=precision)

fsdp_mixed_precision = MixedPrecision(
    param_dtype=precision,
    reduce_dtype=torch.float32,
    buffer_dtype=precision,
)

```

**Comment by PiotrDabkowski** [comment]
@timmoon10 I think the community would *greatly* benefit from an e2e example on how to train a 7B model on H100 node. This is the main purpose of this lib - to train large models quickly. Yet there is not a single example on how to do it - instead we have a MNIST example...
Ideally, a simple pure PyTorch+TE file without any "framework" dependencies like compose of fabric.

**Comment by ksivaman** [comment]
@PiotrDabkowski, please take a look at [NeMo](https://github.com/NVIDIA/NeMo), which provides the exact scripts and tools to be able to do this.

**Comment by jramapuram** [comment]
@ksivaman : AFAIK NeMo uses tensor parallelism which requires manual changes to layers and arch whereas FSDP is pretty generic and more easy to use.

**Comment by halilakin** [comment]
I am testing TE modules' compatibility with FSDP, however running into some issues.

See the following minimal repro code which throws out 

```
 NVTE_DISABLE_NVRTC=1 NVTE_TORCH_COMPILE=0 CUDA_VISIBLE_DEVICES=0,1 python repro.py
FullyShardedDataParallel(
  (_fsdp_wrapped_module): Net(
    (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))
    (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
    (fc1): Linear()
    (fc2): Linear()
    (layer_norm1): LayerNorm()
  )
)
Traceback (most recent call last):
  File "/home/hakin/evolutionaryscale/test.py", line 102, in <module>
    mp.spawn(fsdp_main, args=(WORLD_SIZE,), nprocs=WORLD_SIZE, join=True)
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/hakin/evolutionaryscale/test.py", line 96, in fsdp_main
    train(model, rank, world_size, train_loader, optimizer, epoch)
  File "/home/hakin/evolutionaryscale/test.py", line 59, in train
    output = model(data)
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hakin/evolutionaryscale/test.py", line 49, in forward
    output = F.log_softmax(x, dim=1)
  File "/home/hakin/micromamba/envs/es_te/lib/python3.10/site-packages/torch/nn/functional.py", line 1932, in log_softmax
    ret = input.log_softmax(dim)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```


You can try it with


```
import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import transformer_engine.pytorch as te
from torch.optim.lr_scheduler import StepLR
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, TensorDataset, DistributedSampler
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP


def setup(rank, world_size):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "12355"
    dist.init_process_group("nccl", rank=rank, world_size=world_size)


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)

        # self.fc1 = nn.Linear(9216, 128)
        # self.fc2 = nn.Linear(128, 10)
        self.fc1 = te.Linear(9216, 128)
        self.fc2 = te.Linear(128, 10)

        # self.layer_norm1 = nn.LayerNorm(128)
        self.layer_norm1 = te.LayerNorm(128)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = torch.flatten(x, 1)
        x = self.fc1(x)

        x = self.layer_norm1(x)

        x = F.relu(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output


def train(model, rank, world_size, train_loader, optimizer, epoch):
    model.train()
    ddp_loss = torch.zeros(2).to(rank)
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(rank), target.to(rank)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target, reduction="sum")
        loss.backward()
        optimizer.step()
        ddp_loss[0] += loss.item()
        ddp_loss[1] += len(data)

    dist.all_reduce(ddp_loss, op=dist.ReduceOp.SUM)
    if rank == 0:
        print("Train Epoch: {} \tLoss: {:.6f}".format(epoch, ddp_loss[0] / ddp_loss[1]))


def fsdp_main(rank, world_size):
    setup(rank, world_size)

    num_samples_train = 6000
    x_train = torch.randn(num_samples_train, 1, 28, 28)
    y_train = torch.randint(0, 10, (num_samples_train,))

    train_data = TensorDataset(x_train, y_train)
    train_sampler = DistributedSampler(
        train_data, rank=rank, num_replicas=world_size, shuffle=True
    )
    train_loader = DataLoader(train_data, batch_size=64, sampler=train_sampler)

    torch.cuda.set_device(rank)
    model = Net().to(rank)

    # model = DDP(model)
    model = FSDP(model)
    if torch.distributed.get_rank()==0:
        print(model)

    optimizer = optim.Adadelta(model.parameters(), lr=0.1)
    scheduler = StepLR(optimizer, step_size=1, gamma=0.7)

    for epoch in range(1, 10):
        train(model, rank, world_size, train_loader, optimizer, epoch)
        scheduler.step()


if __name__ == "__main__":
    WORLD_SIZE = torch.cuda.device_count()
    mp.spawn(fsdp_main, args=(WORLD_SIZE,), nprocs=WORLD_SIZE, join=True)

```

This issue happens with te.LayerNorm but not with te.Linear. Any ideas what is going on here? @timmoon10

**Comment by naveenkumarmarri** [comment]
@jramapuram were you able to train FSDP with FP8?

**Comment by denera** [comment]
@yongyanrao #596 recently added support for deferred initialization via `device='meta'` to improve FSDP support. This feature delays memory allocation on device until the FSDP wrap internally calls `reset_parameters()` after sharding the model weights, which ensures that TE modules are not duplicated on every device upon initialization.

We also introduced [a small FSDP example](https://github.com/NVIDIA/TransformerEngine/tree/main/examples/pytorch/fsdp) in the repo as part of this effort to demonstrate how to use FSDP with TE modules. It works out of the box with `fp8_autocast()`, with the requirement that `fp8_autocast(...,fp8_group=...)` gets the same process group as FSDP (both will default to the world group if none given).

**Comment by denizokt** [comment]
@denera Thank you for the feature! This will be super helpful for us too. Just a question, are there any additional steps needed to take to make primary_weights_in_fp8 work with FSDP? Or should it work out of the box?

Thank you!

**Comment by denera** [comment]
@denizokt [`fp8_model_init()`](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/api/pytorch.html#transformer_engine.pytorch.fp8_model_init) is not supported with FSDP at the moment.

NCCL itself does not support 8-bit floats (see [this discussion](https://github.com/NVIDIA/nccl/issues/1026 for more detail) and FSDP needs to upcast TE Fp8 weights to Fp16 for all-gathers and reduce-scatters, which it cannot do until PyTorch starts natively supporting Fp8 tensors.

The workaround for this limitation is what already happens in TE when `primary_weights_in_fp8 = False`. TE modules maintain their own Fp8 weight copies, update them with the primary Fp16/Bf16 weights during the forward pass, and stash the Fp8 transposed-weights into the PyTorch autograd context to re-use it during the backward pass.

**Comment by denizokt** [comment]
@denera Thank you for the information, this makes a lot of sense.
