### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by sudy-super** [NVIDIA/TransformerEngine#526]
### Environment:
Ubuntu 20.04, python 3.8.10, cuda 11.7

### Reproduce:
Run this command:
```
pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable
```
### Expected operation:
Successful installation of transformer-engine.
### Output:
```
Defaulting to user installation because normal site-packages is not writeable
WARNING: Ignoring invalid distribution -riton (/home/suddy/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -riton (/home/suddy/.local/lib/python3.8/site-packages)
Collecting git+https://github.com/NVIDIA/TransformerEngine.git@stable
  Cloning https://github.com/NVIDIA/TransformerEngine.git (to revision stable) to /tmp/pip-req-build-hplbrm_2
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/TransformerEngine.git /tmp/pip-req-build-hplbrm_2
  Running command git checkout -b stable --track origin/stable
  Switched to a new branch 'stable'
  Branch 'stable' set up to track remote branch 'stable' from 'origin'.
  Resolved https://github.com/NVIDIA/TransformerEngine.git to commit 66d91d5219f295ec1e2e714a4926ddb67a2b8f80
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydantic in /home/suddy/.local/lib/python3.8/site-packages (from transformer-engine==1.0.0+66d91d5) (1.10.12)
Requirement already satisfied: typing-extensions>=4.2.0 in /home/suddy/.local/lib/python3.8/site-packages (from pydantic->transformer-engine==1.0.0+66d91d5) (4.7.1)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [142 lines of output]
      running bdist_wheel
      running build
      running build_py
      Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
      Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/transformer_engine
      copying transformer_engine/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine
      creating build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/recipe.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      creating build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/attention.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/float8_tensor.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      creating build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/recompute.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/cpp_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/constants.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/fp8_buffer.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/profile.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      copying transformer_engine/paddle/distributed.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle
      creating build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/fused_attn.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      creating build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/transpose.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/fused_attn.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/activation.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/cast.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/normalization.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/gemm.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/cpp_extensions
      creating build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/base.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/linear.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/rmsnorm.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_mlp.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_linear.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/_common.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch/module
      creating build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/base.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/linear.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm_mlp.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm_linear.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/attention.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/paddle/layer
      creating build/lib.linux-x86_64-3.8/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/module.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/praxis
      creating build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/module.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      running build_ext
      Building CMake extension transformer_engine
      Running command /home/suddy/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -S /tmp/pip-req-build-hplbrm_2/transformer_engine -B /tmp/tmpgwzhvcd9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-hplbrm_2/build/lib.linux-x86_64-3.8 -GNinja -Dpybind11_DIR=/home/suddy/.local/lib/python3.8/site-packages/pybind11/share/cmake/pybind11
      -- The CUDA compiler identification is unknown
      -- The CXX compiler identification is GNU 9.4.0
      CMake Error at CMakeLists.txt:15 (project):
        No CMAKE_CUDA_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
        path to the compiler, or to the compiler name if it is in the PATH.


      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-req-build-hplbrm_2/setup.py", line 353, in _build_cmake
          subprocess.run(command, cwd=build_dir, check=True)
        File "/usr/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/home/suddy/.local/lib/python3.8/site-packages/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-hplbrm_2/transformer_engine', '-B', '/tmp/tmpgwzhvcd9', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-hplbrm_2/build/lib.linux-x86_64-3.8', '-GNinja', '-Dpybind11_DIR=/home/suddy/.local/lib/python3.8/site-packages/pybind11/share/cmake/pybind11']' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-hplbrm_2/setup.py", line 624, in <module>
          main()
        File "/tmp/pip-req-build-hplbrm_2/setup.py", line 609, in main
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/suddy/.local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-hplbrm_2/setup.py", line 383, in run
          ext._build_cmake(
        File "/tmp/pip-req-build-hplbrm_2/setup.py", line 355, in _build_cmake
          raise RuntimeError(f"Error when running CMake: {e}")
      RuntimeError: Error when running CMake: Command '['/home/suddy/.local/lib/python3.8/site-packages/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-hplbrm_2/transformer_engine', '-B', '/tmp/tmpgwzhvcd9', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-hplbrm_2/build/lib.linux-x86_64-3.8', '-GNinja', '-Dpybind11_DIR=/home/suddy/.local/lib/python3.8/site-packages/pybind11/share/cmake/pybind11']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine
  Running setup.py clean for transformer-engine
Failed to build transformer-engine
ERROR: Could not build wheels for transformer-engine, which is required to install pyproject.toml-based projects
WARNING: Ignoring invalid distribution -riton (/home/suddy/.local/lib/python3.8/site-packages)
  ```

**Comment by ptrendx** [comment]
The error is
```
CMake Error at CMakeLists.txt:15 (project):
        No CMAKE_CUDA_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
        path to the compiler, or to the compiler name if it is in the PATH.
```
Where do you have CUDA installed? Seems that CMake cannot find it.
Also, CUDA 11.7 is unfortunately too old for Transformer Engine - we require CUDA 11.8+, since 11.8 introduced Hopper and FP8 support.
