### ISSUE TITLE
Installation errors on Ampere GPUs 

### ISSUE THREAD

**Issue by realAsma** [NVIDIA/TransformerEngine#69]
Is there a `TransformerEngine` source version I can use to install on Ampere GPUs?
It seems that the default installation requires CUDA with FP8  which is not supported on Ampere GPUs. - Please correct me if I am wrong.

**Comment by ptrendx** [comment]
I assume the error you encountered was lack of `cuda_fp8.h` include file - this most probably means that your CUDA Toolkit installation is too old. Transformer Engine requires CUDA 11.8 and you can use it on Ampere (FP8-specific features are limited to Hopper, but everything else should work fine).

**Comment by carmocca** [comment]
Upgrading to CUDA 12.1 allowed me to install it.

Perhaps this comment is outdated and should be updated in the installation instructions

> Transformer Engine requires CUDA 11.8

**Comment by easonfzw** [comment]
> Upgrading to CUDA 12.1 allowed me to install it.
> 
> Perhaps this comment is outdated and should be updated in the installation instructions
> 
> > Transformer Engine requires CUDA 11.8

@carmocca `root@82f6c88b7ad1:~/vicuna/FastChat-transformerEngine/TransformerEngine# pip install --upgrade git+https://github.com/NVIDIA/TransformerEngine.git@stable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/NVIDIA/TransformerEngine.git@stable
  Cloning https://github.com/NVIDIA/TransformerEngine.git (to revision stable) to /tmp/pip-req-build-gi_25fj3
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/TransformerEngine.git /tmp/pip-req-build-gi_25fj3
  Running command git checkout -b stable --track origin/stable
  Switched to a new branch 'stable'
  Branch 'stable' set up to track remote branch 'stable' from 'origin'.
  Resolved https://github.com/NVIDIA/TransformerEngine.git to commit 8e5f00f203ee518961bfb8febb017a2ffcc1d6b3
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydantic in /usr/local/lib/python3.8/dist-packages (from transformer-engine==0.8.0) (1.10.7)
Requirement already satisfied: flash-attn>=1.0.2 in /usr/local/lib/python3.8/dist-packages (from transformer-engine==0.8.0) (1.0.4)
Requirement already satisfied: torch in /usr/local/lib/python3.8/dist-packages (from flash-attn>=1.0.2->transformer-engine==0.8.0) (2.1.0a0+fe05266)
Requirement already satisfied: einops in /usr/local/lib/python3.8/dist-packages (from flash-attn>=1.0.2->transformer-engine==0.8.0) (0.6.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from flash-attn>=1.0.2->transformer-engine==0.8.0) (23.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.8/dist-packages (from pydantic->transformer-engine==0.8.0) (4.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (3.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.8/dist-packages (from torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.8/dist-packages (from torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (2.6.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2->torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.8/dist-packages (from sympy->torch->flash-attn>=1.0.2->transformer-engine==0.8.0) (1.3.0)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [115 lines of output]
      /usr/local/lib/python3.8/dist-packages/setuptools/dist.py:530: UserWarning: Normalizing '0.8.0
      ' to '0.8.0'
        warnings.warn(tmpl.format(**locals()))
      running bdist_wheel
      /usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/transformer_engine
      copying transformer_engine/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine
      creating build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/recipe.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/common
      creating build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax
      creating build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/cpp_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/module.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/pytorch
      creating build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/constants.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/fp8.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/jit.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/module.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/softmax.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      copying transformer_engine/tensorflow/utils.py -> build/lib.linux-x86_64-3.8/transformer_engine/tensorflow
      creating build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/__init__.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/module.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/transformer.py -> build/lib.linux-x86_64-3.8/transformer_engine/jax/flax
      running build_ext
      Building CMake extensions!
      Running CMake in build/temp.linux-x86_64-3.8/Release:
      cmake /tmp/pip-req-build-gi_25fj3/transformer_engine -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-gi_25fj3/build/lib.linux-x86_64-3.8 -GNinja
      cmake --build . --config Release
      CMake Error at CMakeLists.txt:15 (project):
        Running
      
         '/usr/local/bin/ninja' '--version'
      
        failed with:
      
      
      
      
      CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-gi_25fj3/build/temp.linux-x86_64-3.8/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-gi_25fj3/setup.py", line 413, in <module>
          setup(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/dist-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-gi_25fj3/setup.py", line 371, in run
          self.cmake_build_extensions.run()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/local/lib/python3.8/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-req-build-gi_25fj3/setup.py", line 330, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-gi_25fj3/transformer_engine', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-gi_25fj3/build/lib.linux-x86_64-3.8', '-GNinja']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine
  Running setup.py clean for transformer-engine
Failed to build transformer-engine
ERROR: Could not build wheels for transformer-engine, which is required to install pyproject.toml-based projects
root@82f6c88b7ad1:~/vicuna/FastChat-transformerEngine/TransformerEngine# 
`
Hello, I executed pip install --upgrade git+https://github.com/NVIDIA/TransformerEngine.git@stable in the nvcr.io/nvidia:23.04-py3 container, and the above error occurred. What is the reason? My cuda is version 12.1 H100 machine, Looking forward to your reply

**Comment by brando90** [comment]
> Upgrading to CUDA 12.1 allowed me to install it.
> 
> Perhaps this comment is outdated and should be updated in the installation instructions
> 
> > Transformer Engine requires CUDA 11.8

what commands did you use?
