### ISSUE TITLE
The package name passed to `find_package_handle_standard_args` (LIBRARY) does not match the name of the calling package (CUDNN)

### ISSUE THREAD

**Issue by shanepeckham** [NVIDIA/TransformerEngine#752]
When trying to install I get this error consistently, despite setting CUDA_PATH and other build fail suggestions:

`Running command /tmp/pip-req-build-22tuuzyi/.eggs/cmake-3.29.0.1-py3.11-linux-x86_64.egg/cmake/data/bin/cmake -S /tmp/pip-req-build-22tuuzyi/transformer_engine -B /tmp/tmpejwcs22t -DPython_EXECUTABLE=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/bin/python -DPython_INCLUDE_DIR=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/include/python3.11 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-22tuuzyi/build/lib.linux-x86_64-cpython-311 -GNinja
      -- The CUDA compiler identification is NVIDIA 12.0.140
      -- The CXX compiler identification is GNU 13.2.0
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found CUDAToolkit: /usr/include (found version "12.0.140")
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- cudnn found at /usr/lib/x86_64-linux-gnu/libcudnn.so.
      CMake Warning (dev) at /tmp/pip-req-build-22tuuzyi/.eggs/cmake-3.29.0.1-py3.11-linux-x86_64.egg/cmake/data/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
        The package name passed to `find_package_handle_standard_args` (LIBRARY)
        does not match the name of the calling package (CUDNN).  This can lead to
        problems in calling code that expects `find_package` result variables
        (e.g., `_FOUND`) to follow a certain pattern.
      Call Stack (most recent call first):
        cmake/FindCUDNN.cmake:44 (find_package_handle_standard_args)
        CMakeLists.txt:24 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found LIBRARY: /usr/include/x86_64-linux-gnu
      -- cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
      -- cuDNN: /usr/include/x86_64-linux-gnu
      -- cudnn_adv_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.
      -- cudnn_adv_train found at /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.
      -- cudnn_cnn_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.
      -- cudnn_cnn_train found at /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.
      -- cudnn_ops_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.
      -- cudnn_ops_train found at /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.
      -- Found Python: /mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/bin/python (found version "3.11.8") found components: Interpreter Development.Module
      CMake Error at common/CMakeLists.txt:77 (list):
        list GET given empty list
      
      
      -- JAX support: OFF
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-req-build-22tuuzyi/setup.py", line 356, in _build_cmake
          subprocess.run(command, cwd=build_dir, check=True)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/tmp/pip-req-build-22tuuzyi/.eggs/cmake-3.29.0.1-py3.11-linux-x86_64.egg/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-22tuuzyi/transformer_engine', '-B', '/tmp/tmpejwcs22t', '-DPython_EXECUTABLE=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/bin/python', '-DPython_INCLUDE_DIR=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/include/python3.11', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-22tuuzyi/build/lib.linux-x86_64-cpython-311', '-GNinja']' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-22tuuzyi/setup.py", line 629, in <module>
          main()
        File "/tmp/pip-req-build-22tuuzyi/setup.py", line 614, in main
          setuptools.setup(
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-22tuuzyi/setup.py", line 386, in run
          ext._build_cmake(
        File "/tmp/pip-req-build-22tuuzyi/setup.py", line 358, in _build_cmake
          raise RuntimeError(f"Error when running CMake: {e}")
      RuntimeError: Error when running CMake: Command '['/tmp/pip-req-build-22tuuzyi/.eggs/cmake-3.29.0.1-py3.11-linux-x86_64.egg/cmake/data/bin/cmake', '-S', '/tmp/pip-req-build-22tuuzyi/transformer_engine', '-B', '/tmp/tmpejwcs22t', '-DPython_EXECUTABLE=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/bin/python', '-DPython_INCLUDE_DIR=/mnt/38ae7fe1-6107-471a-b4f0-50874b359b32/envs/megatron/include/python3.11', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-22tuuzyi/build/lib.linux-x86_64-cpython-311', '-GNinja']' returned non-zero exit status 1.
      [end of output]
`

**Comment by ptrendx** [comment]
Hi @shanepeckham, could you tell me which version of cuDNN you are using and how you installed it?

**Comment by ptrendx** [comment]
PR #831 was merged that should help with those issues - could you try with the current main branch?

**Comment by sbhavani** [comment]
PR #831 should address the cuDNN warning in this issue by removing TE's old custom `FindCUDNN.cmake` and switching to cuDNN frontend's CMake logic.

One related snag remains: the `list GET given empty list` error appears to be from assuming `CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES` is always populated which may not be the case if nvcc is not installed. 

A follow-up hardening fix could fall back to CMake's `CUDAToolkit_INCLUDE_DIRS` before calling `list(GET ...)`, so the build only fails if CMake cannot determine CUDA include directories at all.
