### ISSUE TITLE
Build fails when using jax NGC image

### ISSUE THREAD

**Issue by bmac3** [NVIDIA/TransformerEngine#767]
Hello,
Thanks so much for making this project, it looks like really exciting stuff. I'm currently having some trouble installing the library and can't quite figure out what's going wrong. For context I am using an L40 GPU with cuda 12.2 installed and driver version 535.161, and I pulled the following jax NGC image: nvcr.io/nvidia/jax:23.10-py3. When I run:

```
NVTE_FRAMEWORK=jax
pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable
```

I get the following output:

```
Collecting git+https://github.com/NVIDIA/TransformerEngine.git@stable
  Cloning https://github.com/NVIDIA/TransformerEngine.git (to revision stable) to /tmp/pip-req-build-wqpvid2m
  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA/TransformerEngine.git /tmp/pip-req-build-wqpvid2m
  Running command git checkout -b stable --track origin/stable
  Switched to a new branch 'stable'
  Branch 'stable' set up to track remote branch 'stable' from 'origin'.
  Resolved https://github.com/NVIDIA/TransformerEngine.git to commit 6a9edc38bf9b941b7d369af5103fa8fe0b121d61
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: flax>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from transformer-engine==1.5.0+6a9edc3) (0.7.4)
Requirement already satisfied: jax in /usr/local/lib/python3.10/dist-packages (from transformer-engine==1.5.0+6a9edc3) (0.4.17.dev20231020)
Collecting pydantic (from transformer-engine==1.5.0+6a9edc3)
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (1.26.1)
Requirement already satisfied: msgpack in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (1.0.7)
Requirement already satisfied: optax in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.1.7)
Requirement already satisfied: orbax-checkpoint in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.4.1)
Requirement already satisfied: tensorstore in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.1.46)
Requirement already satisfied: rich>=11.1 in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (13.6.0)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.10/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (4.8.0)
Requirement already satisfied: PyYAML>=5.4.1 in /usr/lib/python3/dist-packages (from flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (5.4.1)
Requirement already satisfied: ml-dtypes>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from jax->transformer-engine==1.5.0+6a9edc3) (0.3.1)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.10/dist-packages (from jax->transformer-engine==1.5.0+6a9edc3) (3.3.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from jax->transformer-engine==1.5.0+6a9edc3) (1.11.3)
Collecting annotated-types>=0.4.0 (from pydantic->transformer-engine==1.5.0+6a9edc3)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.16.3 (from pydantic->transformer-engine==1.5.0+6a9edc3)
  Using cached pydantic_core-2.16.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (2.16.1)
Requirement already satisfied: absl-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from optax->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (2.0.0)
Requirement already satisfied: chex>=0.1.5 in /usr/local/lib/python3.10/dist-packages (from optax->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.1.84)
Requirement already satisfied: jaxlib>=0.1.37 in /usr/local/lib/python3.10/dist-packages (from optax->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.4.17.dev20231020)
Requirement already satisfied: etils[epath,epy] in /usr/local/lib/python3.10/dist-packages (from orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (1.5.1)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.10/dist-packages (from orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (1.5.8)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (4.24.4)
Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chex>=0.1.5->optax->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.12.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (0.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (2023.9.2)
Requirement already satisfied: importlib_resources in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (6.1.0)
Requirement already satisfied: zipp in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.7.1->transformer-engine==1.5.0+6a9edc3) (3.17.0)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Using cached pydantic_core-2.16.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Building wheels for collected packages: transformer-engine
  Building wheel for transformer-engine (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [190 lines of output]
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/transformer_engine
      copying transformer_engine/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine
      copying transformer_engine/_version.py -> build/lib.linux-x86_64-3.10/transformer_engine
      creating build/lib.linux-x86_64-3.10/transformer_engine/common
      copying transformer_engine/common/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/common
      copying transformer_engine/common/utils.py -> build/lib.linux-x86_64-3.10/transformer_engine/common
      creating build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/dot.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/fp8.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/layernorm.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/mlp.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/sharding.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/softmax.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/cpp_extensions.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      copying transformer_engine/jax/fused_attn.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax
      creating build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/constants.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/cpp_extensions.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/distributed.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/fp8.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/fp8_buffer.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/profile.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/recompute.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      copying transformer_engine/paddle/utils.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle
      creating build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/constants.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/cpu_offload.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/distributed.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/export.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/float8_tensor.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/fp8.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/jit.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/numerics_debug.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/softmax.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/te_onnx_extensions.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/utils.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/attention.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      copying transformer_engine/pytorch/transformer.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch
      creating build/lib.linux-x86_64-3.10/transformer_engine/common/recipe
      copying transformer_engine/common/recipe/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/common/recipe
      creating build/lib.linux-x86_64-3.10/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/module.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/flax
      copying transformer_engine/jax/flax/transformer.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/flax
      creating build/lib.linux-x86_64-3.10/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/module.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/praxis
      copying transformer_engine/jax/praxis/transformer.py -> build/lib.linux-x86_64-3.10/transformer_engine/jax/praxis
      creating build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/attention.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/base.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm_linear.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/layernorm_mlp.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/linear.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/rmsnorm.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/softmax.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      copying transformer_engine/paddle/layer/transformer.py -> build/lib.linux-x86_64-3.10/transformer_engine/paddle/layer
      creating build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/activation.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/cast.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/fused_attn.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/normalization.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/transpose.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      copying transformer_engine/pytorch/cpp_extensions/gemm.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/cpp_extensions
      creating build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/__init__.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/_common.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/rmsnorm.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/base.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_linear.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/layernorm_mlp.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      copying transformer_engine/pytorch/module/linear.py -> build/lib.linux-x86_64-3.10/transformer_engine/pytorch/module
      running build_ext
      Building CMake extension transformer_engine
      Running command /usr/bin/cmake -S /tmp/pip-req-build-wqpvid2m/transformer_engine -B /tmp/pip-req-build-wqpvid2m/build/cmake -DPython_EXECUTABLE=/usr/bin/python3 -DPython_INCLUDE_DIR=/usr/include/python3.10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-wqpvid2m/build/lib.linux-x86_64-3.10 -DENABLE_JAX=ON -Dpybind11_DIR=/tmp/pip-req-build-wqpvid2m/.eggs/pybind11-2.12.0-py3.10.egg/pybind11/share/cmake/pybind11
      -- The CUDA compiler identification is NVIDIA 12.2.91
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.91")
      -- Looking for C++ include pthread.h
      -- Looking for C++ include pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- cudnn found at /usr/lib/x86_64-linux-gnu/libcudnn.so.
      CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
        The package name passed to `find_package_handle_standard_args` (LIBRARY)
        does not match the name of the calling package (CUDNN).  This can lead to
        problems in calling code that expects `find_package` result variables
        (e.g., `_FOUND`) to follow a certain pattern.
      Call Stack (most recent call first):
        cmake/FindCUDNN.cmake:44 (find_package_handle_standard_args)
        CMakeLists.txt:24 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found LIBRARY: /usr/include
      -- cuDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
      -- cuDNN: /usr/include
      -- cudnn_adv_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.
      -- cudnn_adv_train found at /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.
      -- cudnn_cnn_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.
      -- cudnn_cnn_train found at /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.
      -- cudnn_ops_infer found at /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.
      -- cudnn_ops_train found at /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.
      -- Found Python: /usr/bin/python3 (found version "3.10.12") found components: Interpreter Development.Module
      -- JAX support: ON
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found pybind11: /tmp/pip-req-build-wqpvid2m/.eggs/pybind11-2.12.0-py3.10.egg/pybind11/include (found version "2.12.0")
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-req-build-wqpvid2m/build/cmake
      Running command /usr/bin/cmake --build /tmp/pip-req-build-wqpvid2m/build/cmake
      [  2%] Building CXX object common/CMakeFiles/transformer_engine.dir/transformer_engine.cpp.o
      [  5%] Building CUDA object common/CMakeFiles/transformer_engine.dir/transpose/cast_transpose.cu.o
      [  8%] Building CUDA object common/CMakeFiles/transformer_engine.dir/transpose/transpose.cu.o
      [ 11%] Building CUDA object common/CMakeFiles/transformer_engine.dir/transpose/cast_transpose_fusion.cu.o
      [ 13%] Building CUDA object common/CMakeFiles/transformer_engine.dir/transpose/transpose_fusion.cu.o
      [ 16%] Building CUDA object common/CMakeFiles/transformer_engine.dir/transpose/multi_cast_transpose.cu.o
      [ 19%] Building CUDA object common/CMakeFiles/transformer_engine.dir/activation/gelu.cu.o
      [ 22%] Building CUDA object common/CMakeFiles/transformer_engine.dir/fused_attn/fused_attn_f16_max512_seqlen.cu.o
      [ 25%] Building CUDA object common/CMakeFiles/transformer_engine.dir/fused_attn/fused_attn_f16_arbitrary_seqlen.cu.o
      Killed
      gmake[2]: *** [common/CMakeFiles/transformer_engine.dir/build.make:188: common/CMakeFiles/transformer_engine.dir/fused_attn/fused_attn_f16_arbitrary_seqlen.cu.o] Error 255
      gmake[1]: *** [CMakeFiles/Makefile2:116: common/CMakeFiles/transformer_engine.dir/all] Error 2
      gmake: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "/tmp/pip-req-build-wqpvid2m/setup.py", line 336, in _build_cmake
          subprocess.run(command, cwd=build_dir, check=True)
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/tmp/pip-req-build-wqpvid2m/build/cmake']' returned non-zero exit status 2.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-wqpvid2m/setup.py", line 611, in <module>
          main()
        File "/tmp/pip-req-build-wqpvid2m/setup.py", line 596, in main
          setuptools.setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-wqpvid2m/setup.py", line 368, in run
          ext._build_cmake(
        File "/tmp/pip-req-build-wqpvid2m/setup.py", line 338, in _build_cmake
          raise RuntimeError(f"Error when running CMake: {e}")
      RuntimeError: Error when running CMake: Command '['/usr/bin/cmake', '--build', '/tmp/pip-req-build-wqpvid2m/build/cmake']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine
  Running setup.py clean for transformer-engine
Failed to build transformer-engine
ERROR: Could not build wheels for transformer-engine, which is required to install pyproject.toml-based projects
```

I also tried to update the jax/jaxlib version and still was not able to successfully build TE. Any insights into how to solve this issue would be much appreciated. If you could direct me to a different image that can build TE for jax that would also solve my problem. Thanks for your time.

**Comment by ptrendx** [comment]
@denera @nouiz Could you help here?

**Comment by denera** [comment]
@bmac3 Could you try this again with the JAX-Toolbox container at `ghcr.io/nvidia/jax:pax`?

It would also be helpful to see the verbose output from `pip install -v ....` for a better trace of the compile failure.

**Comment by bmac3** [comment]
ghcr.io/nvidia/jax:pax worked for me! Thanks so much for the help. I'll mark this as closed now
